### ISSUE TITLE
Datepicker raise errors

### ISSUE THREAD

**Issue by RiveraIsmael** [datalnet/DnetBlazor#6]
If you clic on the picker , and type the date ,after closing the cdk picker raise the error and it doesn't open again

Error:

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Format_BadDateTimeCalendar, 2025/04/31, System.Globalization.GregorianCalendar
System.FormatException: Format_BadDateTimeCalendar, 2025/04/31, System.Globalization.GregorianCalendar
   at System.DateTimeParse.ParseExact(ReadOnlySpan`1 , ReadOnlySpan`1 , DateTimeFormatInfo , DateTimeStyles )
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at Dnet.Blazor.Components.DatePicker.DnetDatePicker.AttachMenu()
   at Dnet.Blazor.Components.DatePicker.DnetDatePicker.ToggleMenu()
   at Dnet.Blazor.Components.DatePicker.DnetDatePicker.SufixContentClicked()
   at Dnet.Blazor.Components.Form.FormEventService.RaiseSufixContentClicked()
   at Dnet.Blazor.Components.Form.DnetFormField.SufixContentClicked()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate , Object )
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object )
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 , EventFieldInfo , EventArgs , Boolean )

**Comment by datalnet** [comment]
Done
